Wrong data are data which are wrong! for example in time(minutes) field, you see 300, which may be 30 minutes but by mistake it is 300.\
There are two ways to solve this problem, to fix them with rules or to remove the whole record.

In [4]:
import pandas as pd

df = {
    "duration": [
        50,
        40,
        50,
        300,
        60],
    "pulse": [
        100,
        140,
        120,
        110,
        100]
}

df = pd.DataFrame(df)

In [7]:
ndf1 = df.copy()
# Set duration 30 in row 3 (index 3)
ndf.loc[3, 'duration'] = 30
ndf1

   duration  pulse
0        50    100
1        40    140
2        50    120
3       300    110
4        60    100

you can loop on your dataset and do as you wish.\
`loc[index, field_name]` can lead you to a specific cell with its index and field name.

In [10]:
ndf2 = df.copy()
for x in ndf2.index:
    if ndf2.loc[x, 'duration']>60:
        ndf2.loc[x, 'duration'] = 60
        # Or you can:
        # ndf2.drop(x, inplace=True)

ndf2

   duration  pulse
0        50    100
1        40    140
2        50    120
3        60    110
4        60    100